### ISSUE TITLE
Device Support: Princess Smart Air Conditioner 9000

### ISSUE THREAD

**Issue by kekonn** [dennis1804/homewizard-climate-hass#10]
I have just bought the above mentioned air conditioner and it uses the HomeWizard Climate app, but I don't see it in the readme under supported devices.

**Comment by kekonn** [comment]
This is the error I get in the log file, when adding my account:

```
Error setting up entry buttock.scout+homewizard@gmail.com for homewizard_climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewizard_climate/__init__.py", line 37, in async_setup_entry
    devices: list[HomeWizardClimateDevice] = await hass.async_add_executor_job(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/homewizard_climate_ws/api/api.py", line 70, in get_devices
    devices_list = list(
                   ^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 210, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 288, in _decode_generic
    res = _decode_generic(type_arg, value, infer_missing)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 258, in _decode_generic
    res = type_(value)
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 711, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: 'airconditioner' is not a valid HomeWizardClimateDeviceType
```

**Comment by dennis1804** [comment]
that's right, this device isn't supported yet, but it seems like it's the same as #8, so i'm closing this one :)
