### ISSUE TITLE
Stops working after core update to 2023.6.3

### ISSUE THREAD

**Issue by railrene** [dennis1804/homewizard-climate-hass#11]
The integration fails evey nw an then since 2023.6.3. Reloading makes it work again for a while. From logs, see the 2023-06-26 12:20:42.844 ERROR:

2023-06-26 11:05:34.483 ERROR (Thread-1849 (connect)) [websocket] Connection to remote host was lost. - goodbye
2023-06-26 11:05:34.489 ERROR (Thread-1848 (connect)) [websocket] Connection to remote host was lost. - goodbye
2023-06-26 11:35:34.639 ERROR (Thread-1946 (connect)) [websocket] Connection to remote host was lost. - goodbye
2023-06-26 11:35:34.647 ERROR (Thread-1945 (connect)) [websocket] Connection to remote host was lost. - goodbye
2023-06-26 12:20:42.844 ERROR (Thread-2042 (connect)) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/homewizard_climate_ws/ws/hw_websocket.py", line 87, in connect
    self._socket_app.run_forever()
  File "/usr/local/lib/python3.11/site-packages/websocket/_app.py", line 364, in run_forever
    raise WebSocketException("socket is already opened")
websocket._exceptions.WebSocketException: socket is already opened
2023-06-26 12:20:46.264 ERROR (Thread-2043 (connect)) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/homewizard_climate_ws/ws/hw_websocket.py", line 87, in connect
    self._socket_app.run_forever()
  File "/usr/local/lib/python3.11/site-packages/websocket/_app.py", line 364, in run_forever
    raise WebSocketException("socket is already opened")
websocket._exceptions.WebSocketException: socket is already opened

Second question while I'm here now anyway: Could the default half-hourly disconnec-loggings (the first four above) be surpressed?

**Comment by PietPiraat80** [comment]
I have the same problem with the same error message.

**Comment by dennis1804** [comment]
Yeah I got it as well, gonna check it. Probably a timing issue in the initializing of the websocket.

**Comment by dennis1804** [comment]
i pushed some changes to the websocket part of this package that might fix it. i'll keep an eye on it.

**Comment by PietPiraat80** [comment]
I'm still losing connection to my dehumidifiers with the following error message:

Logger: websocket
Source: /usr/local/lib/python3.11/site-packages/websocket/_logging.py:64
First occurred: 10 juli 2023 om 16:30:23 (8 occurrences)
Last logged: 10 juli 2023 om 17:30:23

error from callback <bound method HomeWizardClimateWebSocket._on_message of <homewizard_climate_ws.ws.hw_websocket.HomeWizardClimateWebSocket object at 0x7f6d16ca10>>: invalid literal for int() with base 10: 'high'
error from callback <bound method HomeWizardClimateWebSocket._on_message of <homewizard_climate_ws.ws.hw_websocket.HomeWizardClimateWebSocket object at 0x7f60eb7590>>: invalid literal for int() with base 10: 'low'
Connection to remote host was lost. - goodbye

**Comment by PietPiraat80** [comment]
Any thoughts on how to fix the above issue?

**Comment by dennis1804** [comment]
@PietPiraat80, no not yet. i see this error popping up so that probably has something to do with it but needs some more investigation.
`Disconnected: Did not receive auth message within 10 seconds`

**Comment by PietPiraat80** [comment]
regarding `<homewizard_climate_ws.ws.hw_websocket.HomeWizardClimateWebSocket object at 0x7f60eb7590>>: invalid literal for int() with base 10: 'low'` can this problem come from line 293 in climate.py `self._device_web_socket.set_fan_speed(fan_mode)` as I understand it fan_speed in the websocket is a INT while fan_mode is a STR. I have only basic knowledge of coding so it might be nothing.

**Comment by dennis1804** [comment]
small update, i the issue is fixed. it's pushed to the main branch so you should get an update.
restart might be required because of the updated websockets.

after an hour it will try to reconnect and initiate a new websocket client. this takes some time (for me it was a 10-20 seconds) so when you click the button it might not change instantly.
i'll take a look at that and see if i can speed that up, but i'm just happy that i possibly fixed the issue :)

**Comment by m3tc0n** [comment]
Hello Dennis, thanks for the heads up and update. But my IR panel isn't working anymore in HA after the update. I have restarted HA and also reloaded the integration.

**Comment by dennis1804** [comment]
hm weird, if it's not working after a restart of homeassistant, with the latest version (1.0.7) it's probably something with the plugin.
seems strange because i got the same IR panel but as a 400W unit.
please provide some logs and troubleshooting in #18, that's your issue that i closed.
