### ISSUE TITLE
This device has no entities

### ISSUE THREAD

**Issue by adhar1985** [dennis1804/homewizard-climate-hass#23]
I have setup following the readme file and devices are added but they do not have any entity. It used to work fine but recently stopped working and I had to remove and readded the config and now no entities.
I have this in the log if that helpes
`2024-03-26 13:38:59.327 DEBUG (Thread-37 (connect)) [custom_components.homewizard_climate.climate.FANC45BBED55854] State updated, diff: 
2024-03-26 13:38:59.329 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 937, in async_write_ha_state
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Dining Room Fan`

**Comment by Pascal4Games** [comment]
Hey, what devices do you have?
Which version homewizard-climate-hass?
Which version of home assistant?

**Comment by adhar1985** [comment]
Home Assistant Core 2024.3.3

Home Assistant Operating System 12.1
homewizard-climate-hass 1.0.8

I have a Princess 350000 Smart Tower Fan

**Comment by adhar1985** [comment]
Home Assistant Core 2024.3.3
Home Assistant Operating System 12.1 homewizard-climate-hass 1.0.8
I have a Princess 350000 Smart Tower Fan

**Comment by Pascal4Games** [comment]
I tried to create the problem myself (I also have the smart tower fan), but I don't get the problem.
Have you tried deleting the integration and downloading it again after the problem occurred?
And do you remember why it stopped working in the first place?
